### ISSUE TITLE
Problems initializing Monx

### ISSUE THREAD

**Issue by kokujin** [kbrsh/monx#2]
It seems that the way to initialize Monx has changed.
`````
Moon.use(Monx);

const store = new Monx({.....

`````
I am using the latest version in this repository as mention in this post.

https://github.com/kbrsh/moon/issues/138

But I keep on getting this error:

`````
app.js: Uncaught ReferenceError: Monx is not defined

`````
@kbrsh , any idea what I am doing wrong? Thanks

**Comment by LeviSchuck** [comment]
That sounds more like you have not imported it and named the import / require result `Monx`

**Comment by kokujin** [comment]
That's not the case, its already in the global namespace (window.Moon), I am using the browser version defined here
``````
'./node_modules/monx/dist/monx.js'
``````
Then...

`````
const m = Moon.util.m;
Moon.use(window.Monx);

`````
This worked well before I decided to use the newer version

**Comment by kbrsh** [comment]
Can I see a little bit more of the code? @kokujin

**Comment by kokujin** [comment]
Sure, the relevant blocks of code are.
``````
// Test component

     Moon.extend("project-selector", {
         template: templates['selector.html'],
         data: function() {
             return {
                 projects: []
             }
         },
         methods: {
             switchProject: function(val) {
                 var selectWidget = val.target;
                 var t = selectWidget.options[selectWidget.selectedIndex].value;

                 store.dispatch("selectedProject", t);
                 //appTree.set('selectedProject', t);
                 //appTree.commit();
             }
         },
         hooks: {
             init: function() {
                 store.init(this);
             }
         }
     });

 // App
     const app = new Moon({
         root: "#app-moon",
         hooks: {
             init: function() {
                 _log('APP :: init');
                 store.init(this);
             },
             mounted: function() {
                 _log('APP :: mounted');
             },
             updated: function() {
                 _log('APP :: updated');
             }
         }
     });
``````

I have commented several lines of code to start with a clean slate

**Comment by kbrsh** [comment]
Are you using `require` to load Moon or Monx?

**Comment by kokujin** [comment]
No I'm not using require, as I mentioned above, I am using the browser versions in the dist folders for both Moon and Monx. Moon and Monx are automatically in the "window" global namespace.

All my code was working till I changed versions to avoid the problem in the issue.

**Comment by LeviSchuck** [comment]
Is the exception on your moon.use line?

**Comment by kbrsh** [comment]
Alright @kokujin I'm going to need a reproduction to investigate further.

**Comment by kokujin** [comment]
@LeviSchuck, no, the exception is thrown when  when I create the main Moon app instance.
@kbrsh, then I'll wait for you to finish V1 then. It would be problematic to strip all unnecessary lines as I've done in this post to place in a fiddle.

Maybe @LeviSchuck could explain his workaround to me again? That would let me continue till @kbrsh is finished with V1.

**Comment by LeviSchuck** [comment]
My workaround was not about initializing, but having the DOM rebuild when I changed nested items.

Having a stack trace would be incredibly useful. Even if it's just a screeshot of whatever in chrome.

**Comment by kokujin** [comment]
@LeviSchuck , that's what I'm talking about too, this issue that you opened, https://github.com/kbrsh/moon/issues/138

**Comment by kbrsh** [comment]
@kokujin v1 is pretty much done in regards to the virtual DOM engine and observer system. A stack trace of the error or a screenshot of the developer tools console would be very helpful.

**Comment by LeviSchuck** [comment]
@kokujin The issue there was that not ALL of the components would re-render appropriately when I changed nested data.

The real, not-hacky solution was along these lines:

```js
actions: {
  thing: function(state, data) {
    var infos = state.infos;
    infos[data.key] = data.value;
    state.infos = infos; // This is important, it will use Monx's `set` implementation
  }
}
```

What I had before was like this, but it wouldn't call the re-render.

```js
actions: {
  thing: function(state, data) {
    state.infos[data.key] = data.value;
  }
}
```

---

Again.. please provide a stack trace

**Comment by kokujin** [comment]
Ok. I have stripped my code to a bare minimum to demonstrate. So using the latest Moon and Monx:

``````
 Moon.use(window.Monx);

     // Setup store
     const store = new Monx({
         state: {
             projects: [],
             selectedProject: null
         },
         actions: {
             // projects
             updateProjects: function(state, payload) {
                 state.projects = payload;
             },
             selectProject: function(state, payload) {
                 state.selectedProject = payload;
             }
         }
     });

    
     fetch('/projects')
         .then(function(response) {
             return response.json();
         }).then(function(json) {
             store.dispatch("updateProjects", json.data);
         }).catch(function(ex) {
             _log('parsing failed ex: ', ex)
         });

 
     Moon.extend("project-selector", {
         template: templates['selector.html'],
         data: function() {
             return {
                 projects: []
             }
         },
         methods: {
             switchProject: function(val) {
                 var selectWidget = val.target;
                 var t = selectWidget.options[selectWidget.selectedIndex].value;
                 store.dispatch("selectedProject", t);
             }
         },
         hooks: {
             init: function() {
                 store.init(this);
             }
         }
     });

   
     const app = new Moon({
         root: "#app-moon",
         hooks: {
             init: function() {
                 _log('APP :: init');
                 store.init(this);
             },
             mounted: function() {
                 _log('APP :: mounted');
             },
             updated: function() {
                 _log('APP :: updated');
             }
         }
     });
 });
``````

It seems as if it's the way I am using "Moon.use". Here is the trace in the console

``````

app.js:sourcemap:2794 Uncaught TypeError: Cannot read property 'init' of undefined
    at Function.Moon.use (app.js:sourcemap:2794)
    at HTMLDocument.<anonymous> (app.js:sourcemap:8724)
Moon.use @ app.js:sourcemap:2794
(anonymous) @ app.js:sourcemap:8724
Navigated to http://localhost:3030/

``````

**Comment by kbrsh** [comment]
Are you using Webpack or Browserify?

**Comment by kokujin** [comment]
Nothing complicated; I am using a Gulp task that concatenates and minifies all vendor and my custom scripts. into one file for loading. Works very well with the older versions of Moon and Monx

**Comment by kbrsh** [comment]
Are you sure `window.Monx` is there? Try logging it and ensure that it isn't `undefined`

**Comment by kokujin** [comment]
Sorry it took so long, this is embarrassing, you are right, window.Monx is undefined. This was working code using the old version

**Comment by kokujin** [comment]
I would like to apologize for the false alarm. I took a look at the source that I was compiling an noticed the init signatures were different, with closer inspection, I noticed I had mistaken Moon for Monx.

Code loads and runs without errors now. Thanks for your help
