### ISSUE TITLE
Is the store object available inside the component instance?

### ISSUE THREAD

**Issue by gernest** [kbrsh/monx#4]
I would like to dispatch actions inside my component method.  I can access store inside the template, I was wondering if there is a way to access the store object so I can dispatch actions inside the component methods.

**Comment by kbrsh** [comment]
Yes, it is available inside of an instance. The only reason you can access the store inside of a template is because Monx will define the `store` object inside of the `data` of a component that has a store.

```js
const store = this.get("store");
```

**Comment by gernest** [comment]
Thanks
